version: '3.8'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  default:
    name: yfk-courier-network
    driver: bridge