export interface Root {
  code: number
  status: string
  message: string
  data: Data
}

export interface Data {
  phone: string
  message: string
  data: Data2
}

export interface Data2 {
  id: number
  parentcode: number
  barcode: number
  seq: number
  kodeproduksi: string
  sesi: string
  prioritas: number
  productcategory: number
  tipeitem: string
  tipemenu: string
  qty: number
  request: string
  cutlery: number
  tanggal: string
  branch: number
  kloter: string
  customer: number
  province: number
  city: number
  district: number
  village: number
  postcode: number
  address: string
  kurir: number
  kurirdmd: number
  kurirdlv: any
  scan_kurir: number
  scan_prepare: any
  scan_qc: any
  created_user: number
  updated_user: any
  inisial: string
  generate_code: string
  status: string
  created_at: string
  updated_at: string
  gambar: any
  penerima: any
  description: any
  sts_kirim: string
  custom_request: any
  is_permission: string
  is_called: string
  scan_at: any
  done_at: any
  pickup_at: string
  latitude: any
  longitude: any
  datadetail: Datadetail
  datacustomer: Datacustomer
  datakurirdmd: any
  dataorderdeliverylog: Dataorderdeliverylog[]
}

export interface Datadetail {
  id: number
  orderno: string
  invoice: string
  status: string
  tanggal: string
  order: number
  urut: number
  delivery_status: number
  product: number
  productcategory: number
  batch: number
  branch: number
  qty: number
  cutlery: string
  price: number
  tipe: string
  tipeitem: string
  tipemenu: string
  tipetransaksi: string
  waktu: string
  kloter: string
  voucher: any
  partner: any
  customer: number
  province: number
  city: number
  district: number
  village: number
  postcode: number
  address: string
  csaddr: any
  created_user: number
  updated_user: any
  sales: number
  courier: any
  courier_at: any
  qc: any
  qc_at: any
  age: string
  gender: string
  started_at: string
  tgllastorder: any
  prioritas_level: number
  snaptoken: any
  created_at: string
  updated_at: string
  specialrequest: any
  refund_reason_id: any
  custom_request: any
  clrrequest: any
  csstatus: number
  memo: any
  freemeal: string
  tanpa_ayam: string
  tanpa_ikan: string
  tanpa_sapi: string
  tanpa_tahu: string
  tanpa_tempe: string
  tanpa_terong: string
  tanpa_kacang: string
  tanpa_nasi: string
  tanpa_kentang_dan_ubi: string
  tanpa_mie: string
  tanpa_pasta: string
  tanpa_roti: string
  tanpa_udon: string
  tanpa_pedas: string
  tanpa_olahan_susu: string
  tanpa_telur: string
  tanpa_kacang_panjang: string
  tanpa_sayur: string
  tanpa_bawang_goreng: string
  tanpa_jagung: string
  tanpa_ketumbar: string
  tanpa_kecombrang: string
  tanpa_tepung: string
  artsts: string
  stsgn: string
  generate_code: string
  totp: number
  totc: number
  tota: number
  totpca: number
  diabetes: string
  kolesterol: string
  tanpa_karbo: string
  tanpa_salad: string
  tanpa_kacang_kedelai: string
  refund_at: any
  tanpa_tepung_dan_karbo: string
  asam_urat: string
  tanpa_udang: string
  tanpa_ikan_dan_udang: string
  tanpa_jamur: string
  tanpa_meatloaf: string
  tanpa_paha_ayam: string
  tanpa_goreng: string
}

export interface Datacustomer {
  id: number
  uuid: string
  fname: string
  lname: string
  phone: string
  phone_clr: string
  email: string
  dob: string
  age: number
  gender: string
  email_verified_at: string
  two_factor_code: string
  two_factor_expires_at: any
  province: number
  nm_province: string
  city: number
  nm_city: string
  district: number
  village: number
  postcode: number
  address: string
  active: string
  product: number
  membership: string
  membership_at: string
  token_activation: any
  isVerified: number
  phone_verified_at: any
  expired_at: any
  event: string
  csevent: string
  activationcode: string
  activationsignature: string
  prioritas_exp: string
  prioritas_level: number
  status: number
  wl: string
  cholstrl: string
  dbts: string
  wlplus: string
  created_at: string
  updated_at: string
  totalpax: number
  last_order: string
  lastorder: string
}

export interface Dataorderdeliverylog {
  id: number
  barcode: number
  user_id: number
  status: string
  kurir_id: any
  created_at: string
  updated_at: string
}
