export interface User {
  id: number;
  nik: number;
  kitchen: number;
  branch: number;
  department: number;
  division: number;
  position: number;
  partner_id: number | null;
  religion: number;
  liga: string;
  leader: number;
  name: string;
  phone: string;
  email_freshchat: string | null;
  email: string;
  email_verified_at: string | null;
  two_factor_code: string | null;
  two_factor_expires_at: string | null;
  permission: string;
  province: number;
  city: number;
  district: number;
  role: number;
  village: number;
  postcode: number;
  address: string;
  dob: string;
  gender: string;
  gambar: string;
  is_agentactive: string;
  active: string;
  theme: string;
  target_dinner_weekend: string;
  target_dinner_weekday: string;
  target_lunch_weekend: string;
  target_monthly: string;
  target_lunch_weekday: string;
  tarif: number;
  point: number;
  gp: number;
  th_weekday: number;
  th_weekend: number;
  tr: number;
  bpjstk_user: number;
  bpjstk_prsh: number;
  bpjskes_user: number;
  bpjskes_prsh: number;
  bank: number;
  in_at: string;
  out_at: string | null;
  norek: string;
  api_token: string | null;
  lembur: string;
  jatah_cuti: number;
  ukuran_baju: string | null;
  ukuran_sepatu: string | null;
  template_absen?: string;
  vein_absen?: string;
  rfid_absen?: string | null;
  password_absen?: string | null;
  face_absen?: string;
  pin_absen?: number;
  emailperusahaan?: string | null;
  pwdemailperusahaan?: string | null;
  hpperusahaan?: string | null;
  nohpperusahaan?: string | null;
  pwdhpperusahaan?: string | null;
  laptopperusahaan?: string | null;
  pwdlaptopperusahaan?: string | null;
  created_at?: string;
  last_login?: string;
  updated_at?: string;
  datadivision?: {
    id: number;
    inisial: string;
    name: string;
    department: number;
    active: string;
    created_at: string;
    updated_at: string;
    datadepartment?: {
      id: number;
      name: string;
      created_at: string;
      updated_at: string;
    };
  };
  dataposition?: {
    id: number;
    name: string;
    level: number;
    active: string;
    created_at: string;
    updated_at: string;
  };
}
